server:
  port: 9527


eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
  instance:
    instance-id: zuul-gateway-9527

spring:
  application:
    name: springcloud-zuul


zuul:
  routes:
    mydept.service-id: springcloud-provider-dept
    mydept.path: /mydept/**
  ignored-services: springcloud-provider-dept
