server:
  port: 8002

mybatis:
  type-aliases-package: com.lxm.springcloud.pojo
  mapper-locations: classpath:mybatis/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true
  # config-location: classpath:mybatis/mybatis-config.xml

spring:
  application:
    name: springcloud-provider-dept
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/db02?useUnicode=true&characterEncoding=utf-8&setTimezone=Asia/Shanghai
    username: root
    password: root


#eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
    instance:
      instance-id: springcloud-provider-dept-8002

info:
  app.name: springcloud-provider-dept
  company.name: com.lxm.springcloud