server:
  port: 7001
eureka:
  client:
    register-with-eureka: false # 是否注册自己
    fetch-registry: false # 如果为false表示自己就是注册中心
    service-url: # 监控页面
      defaultZone: http://${eureka.instance.hostname}/${server.port}/eureka/
  instance:
    hostname: localhost # 实例名称